Issue 7: Update all Maven dependencies to their latest versions
* Rolling back `com.github.marschall:memoryfilesystem` from `2.1.0` to `0.9.1` due to incompatibilities with JDK11. This will have to be investigated in a follow-up issue, as it causes a problem with timestamps like this:
```
[ERROR] Failures:
[ERROR]   ReadAttributesTest.readAttributesAll:463 expected:<2020-08-23T10:19:52.0635Z> but was:<2020-08-23T21:19:52.635Z>
[ERROR]   ReadAttributesTest.readAttributesFile:92 expected:<2020-08-23T21:19:52.669127Z> but was:<2020-08-23T21:19:52.669Z>
```